repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.7.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.16
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(openfoundry|alembic|sandbox)/.*\.py$
      - id: ruff
        name: ruff-import-sort
        args: [--select, I, --fix]
        files: ^(openfoundry|alembic|sandbox)/.*\.py$
      - id: ruff-format
        files: ^(openfoundry|alembic|sandbox)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-setuptools
          - types-pyyaml
          - types-toml
          - sqlalchemy
          - fastapi
          - alembic
          - types-psycopg2
        entry: mypy --config-file=pyproject.toml openfoundry/
        always_run: true
        pass_filenames: false
        files: ^openfoundry/.*\.py$

  - repo: https://github.com/GitGuardian/ggshield
    rev: v1.41.0
    hooks:
      - id: ggshield
        name: GitGuardian Shield Secret Scan
        entry: ggshield secret scan pre-commit
        language: system
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: frontend-lint
        name: Frontend Lint & Format
        entry: bash -c 'cd frontend && npm run lint:fix'
        language: system
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        pass_filenames: false
