"""add app_port to AppAgentSession table

Revision ID: 12a595ea79d0
Revises: a7c34f893c6d
Create Date: 2025-07-04 18:23:10.959627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a595ea79d0'
down_revision: Union[str, Sequence[str], None] = 'a7c34f893c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as NOT NULL with server_default to fill existing rows
    op.add_column('app_agent_sessions', sa.Column('app_port', sa.Integer(), nullable=False, server_default='8080'))
    # Step 2: Drop the server_default so new rows must explicitly set app_port
    op.alter_column('app_agent_sessions', 'app_port', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_agent_sessions', 'app_port')
    # ### end Alembic commands ###
