"""add databricks connection

Revision ID: 4aad813baecb
Revises: 0decfa45263f
Create Date: 2025-07-11 03:59:59.661870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aad813baecb'
down_revision: Union[str, Sequence[str], None] = '0decfa45263f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add DATABRICKS value to the existing connectiontype enum
    op.execute("ALTER TYPE connectiontype ADD VALUE 'DATABRICKS'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databricks_connections',
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('http_path', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('database', sa.String(), nullable=False),
    sa.Column('schema', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databricks_connections')
    op.execute("ALTER TYPE connectiontype REMOVE VALUE 'DATABRICKS'")
    # ### end Alembic commands ###
