"""add snowflake connection

Revision ID: 7db5502e64ac
Revises: df38390f96e2
Create Date: 2025-07-06 23:35:12.543419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db5502e64ac'
down_revision: Union[str, Sequence[str], None] = 'df38390f96e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SNOWFLAKE', name='connectiontype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snowflake_connections',
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('database', sa.String(), nullable=False),
    sa.Column('warehouse', sa.String(), nullable=False),
    sa.Column('schema', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snowflake_connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
