"""add deployment_port to App table

Revision ID: 6b9a318d2664
Revises: 7db5502e64ac
Create Date: 2025-07-07 19:30:52.672508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9a318d2664'
down_revision: Union[str, Sequence[str], None] = '7db5502e64ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('deployment_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'deployment_port')
    # ### end Alembic commands ###
