"""soft delete app

Revision ID: df38390f96e2
Revises: 12a595ea79d0
Create Date: 2025-07-06 22:12:05.830396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df38390f96e2'
down_revision: Union[str, Sequence[str], None] = '12a595ea79d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'deleted_on')
    # ### end Alembic commands ###
