"""add postgres_connection table

Revision ID: 01f142e6cc0a
Revises: 33953b146e64
Create Date: 2025-07-16 22:05:46.176957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f142e6cc0a'
down_revision: Union[str, Sequence[str], None] = '33953b146e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE connectiontype ADD VALUE IF NOT EXISTS 'POSTGRES'")
    op.create_table('postgres_connections',
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('database', sa.String(), nullable=False),
    sa.Column('schema', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postgres_connections')
    # ### end Alembic commands ###
