"""app connections table

Revision ID: f2007e1fd995
Revises: 4aad813baecb
Create Date: 2025-07-12 00:41:23.411392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2007e1fd995'
down_revision: Union[str, Sequence[str], None] = '4aad813baecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_connections',
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('app_id', 'connection_id')
    )
    op.drop_table('app_connection')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_connection',
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_connection_app_id_fkey')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('app_connection_connection_id_fkey')),
    sa.PrimaryKeyConstraint('app_id', 'connection_id', name=op.f('app_connection_pkey'))
    )
    op.drop_table('app_connections')
    # ### end Alembic commands ###
