"""add agent session, app agent session, and apps tables

Revision ID: 9348104db61d
Revises:
Create Date: 2025-07-01 06:44:53.689906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9348104db61d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('APP_AGENT_SESSION', name='agentsessiontype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STOPPED', name='agentsessionstatus'), nullable=False),
    sa.Column('is_running_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('current_agent', sa.String(), nullable=False),
    sa.Column('last_message_id', sa.String(), nullable=True),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_agent_sessions',
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_agent_sessions')
    op.drop_table('apps')
    op.drop_table('agent_sessions')
    op.execute("DROP TYPE IF EXISTS agentsessionstatus")
    op.execute("DROP TYPE IF EXISTS agentsessiontype")
    # ### end Alembic commands ###
